const categories = { 1: "Sales", 2: "Scam", 5: "Survey", 6: "Robocall", 7: "Donation", 8: "Public Services" }

const countries = [
    { name: "Afghanistan", cc: "af", prefix: 93 },
    { name: "Albania", cc: "al", prefix: 355 },
    { name: "Algeria", cc: "dz", prefix: 213 },
    { name: "American Samoa", cc: "as", prefix: 1684 },
    { name: "Andorra", cc: "ad", prefix: 376 },
    { name: "Angola", cc: "ao", prefix: 244 },
    { name: "Anguilla", cc: "ai", prefix: 1264 },
    { name: "Antigua and Barbuda", cc: "ag", prefix: 1268 },
    { name: "Argentina", cc: "ar", prefix: 54 },
    { name: "Armenia", cc: "am", prefix: 374 },
    { name: "Aruba", cc: "aw", prefix: 297 },
    { name: "Australia", cc: "au", prefix: 61 },
    { name: "Austria", cc: "at", prefix: 43 },
    { name: "Azerbaijan", cc: "az", prefix: 994 },
    { name: "Bahamas", cc: "bs", prefix: 1242 },
    { name: "Bahrain", cc: "bh", prefix: 973 },
    { name: "Bangladesh", cc: "bd", prefix: 880 },
    { name: "Barbados", cc: "bb", prefix: 1246 },
    { name: "Belarus", cc: "by", prefix: 375 },
    { name: "Belgium", cc: "be", prefix: 32 },
    { name: "Belize", cc: "bz", prefix: 501 },
    { name: "Benin", cc: "bj", prefix: 229 },
    { name: "Bermuda", cc: "bm", prefix: 1441 },
    { name: "Bhutan", cc: "bt", prefix: 975 },
    { name: "Bolivia", cc: "bo", prefix: 591 },
    { name: "Bosnia and Herzegovina", cc: "ba", prefix: 387 },
    { name: "Botswana", cc: "bw", prefix: 267 },
    { name: "Brazil", cc: "br", prefix: 55 },
    { name: "British Indian Ocean Territory", cc: "io", prefix: 246 },
    { name: "British Virgin Islands", cc: "vg", prefix: 1284 },
    { name: "Brunei", cc: "bn", prefix: 673 },
    { name: "Bulgaria", cc: "bg", prefix: 359 },
    { name: "Burkina Faso", cc: "bf", prefix: 226 },
    { name: "Burma-Myanmar", cc: "mm", prefix: 95 },
    { name: "Burundi", cc: "bi", prefix: 257 },
    { name: "Cambodia", cc: "kh", prefix: 855 },
    { name: "Cameroon", cc: "cm", prefix: 237 },
    { name: "Canada", cc: "ca", prefix: 1 },
    { name: "Cape Verde", cc: "cv", prefix: 238 },
    { name: "Cayman Islands", cc: "ky", prefix: 1345 },
    { name: "Central African Republic", cc: "cf", prefix: 236 },
    { name: "Chad", cc: "td", prefix: 235 },
    { name: "Chile", cc: "cl", prefix: 56 },
    { name: "China", cc: "cn", prefix: 86 },
    { name: "Christmas Island", cc: "cx", prefix: 6189 },
    { name: "Colombia", cc: "co", prefix: 57 },
    { name: "Comoros", cc: "km", prefix: 269 },
    { name: "Congo", cc: "cg", prefix: 242 },
    { name: "Congo, The Democratic Republic", cc: "cd", prefix: 243 },
    { name: "Cook Islands", cc: "ck", prefix: 682 },
    { name: "Costa Rica", cc: "cr", prefix: 506 },
    { name: "Croatia", cc: "hr", prefix: 385 },
    { name: "Cuba", cc: "cu", prefix: 53 },
    { name: "Cyprus", cc: "cy", prefix: 357 },
    { name: "Czech Republic", cc: "cz", prefix: 420 },
    { name: "Denmark", cc: "dk", prefix: 45 },
    { name: "Djibouti", cc: "dj", prefix: 253 },
    { name: "Dominica", cc: "dm", prefix: 1767 },
    { name: "Dominican Republic", cc: "do", prefix: 1849 },
    { name: "Dominican Republic", cc: "do", prefix: 1829 },
    { name: "Dominican Republic", cc: "do", prefix: 1809 },
    { name: "East Timor", cc: "tl", prefix: 670 },
    { name: "Ecuador", cc: "ec", prefix: 593 },
    { name: "Egypt", cc: "eg", prefix: 20 },
    { name: "El Salvador", cc: "sv", prefix: 503 },
    { name: "Equatorial Guinea", cc: "gq", prefix: 240 },
    { name: "Eritrea", cc: "er", prefix: 291 },
    { name: "Estonia", cc: "ee", prefix: 372 },
    { name: "Ethiopia", cc: "et", prefix: 251 },
    { name: "Faroe Islands", cc: "fo", prefix: 298 },
    { name: "Fiji", cc: "fj", prefix: 679 },
    { name: "Finland", cc: "fi", prefix: 358 },
    { name: "France", cc: "fr", prefix: 33 },
    { name: "French Guiana", cc: "gf", prefix: 594 },
    { name: "French Polynesia", cc: "pf", prefix: 689 },
    { name: "Gabon", cc: "ga", prefix: 241 },
    { name: "Gambia", cc: "gm", prefix: 220 },
    { name: "Georgia", cc: "ge", prefix: 995 },
    { name: "Germany", cc: "de", prefix: 49 },
    { name: "Ghana", cc: "gh", prefix: 233 },
    { name: "Gibraltar", cc: "gi", prefix: 350 },
    { name: "Greece", cc: "gr", prefix: 30 },
    { name: "Greenland", cc: "gl", prefix: 299 },
    { name: "Grenada", cc: "gd", prefix: 1473 },
    { name: "Guadeloupe", cc: "gp", prefix: 590 },
    { name: "Guam", cc: "gu", prefix: 1671 },
    { name: "Guatemala", cc: "gt", prefix: 502 },
    { name: "Guinea", cc: "gn", prefix: 224 },
    { name: "Guinea-Bissau", cc: "gw", prefix: 245 },
    { name: "Guyana", cc: "gy", prefix: 592 },
    { name: "Haiti", cc: "ht", prefix: 509 },
    { name: "Honduras", cc: "hn", prefix: 504 },
    { name: "Hong Kong", cc: "hk", prefix: 852 },
    { name: "Hungary", cc: "hu", prefix: 36 },
    { name: "Iceland", cc: "is", prefix: 354 },
    { name: "India", cc: "in", prefix: 91 },
    { name: "Indonesia", cc: "id", prefix: 62 },
    { name: "Iran", cc: "ir", prefix: 98 },
    { name: "Iraq", cc: "iq", prefix: 964 },
    { name: "Ireland", cc: "ie", prefix: 353 },
    { name: "Israel", cc: "il", prefix: 972 },
    { name: "Italy", cc: "it", prefix: 39 },
    { name: "Ivory Coast", cc: "ci", prefix: 225 },
    { name: "Jamaica", cc: "jm", prefix: 1876 },
    { name: "Japan", cc: "jp", prefix: 81 },
    { name: "Jordan", cc: "jo", prefix: 962 },
    { name: "Kazakhstan", cc: "kz", prefix: 7 },
    { name: "Kenya", cc: "ke", prefix: 254 },
    { name: "Kiribati", cc: "ki", prefix: 686 },
    { name: "Kuwait", cc: "kw", prefix: 965 },
    { name: "Kyrgyzstan", cc: "kg", prefix: 996 },
    { name: "Laos", cc: "la", prefix: 856 },
    { name: "Latvia", cc: "lv", prefix: 371 },
    { name: "Lebanon", cc: "lb", prefix: 961 },
    { name: "Lesotho", cc: "ls", prefix: 266 },
    { name: "Liberia", cc: "lr", prefix: 231 },
    { name: "Libya", cc: "ly", prefix: 218 },
    { name: "Liechtenstein", cc: "li", prefix: 423 },
    { name: "Lithuania", cc: "lt", prefix: 370 },
    { name: "Luxembourg", cc: "lu", prefix: 352 },
    { name: "Macau", cc: "mo", prefix: 853 },
    { name: "Macedonia", cc: "mk", prefix: 389 },
    { name: "Madagascar", cc: "mg", prefix: 261 },
    { name: "Malawi", cc: "mw", prefix: 265 },
    { name: "Malaysia", cc: "my", prefix: 60 },
    { name: "Maldives", cc: "mv", prefix: 960 },
    { name: "Mali", cc: "ml", prefix: 223 },
    { name: "Malta", cc: "mt", prefix: 356 },
    { name: "Marshall Islands", cc: "mh", prefix: 692 },
    { name: "Martinique", cc: "mq", prefix: 596 },
    { name: "Mauritania", cc: "mr", prefix: 222 },
    { name: "Mauritius", cc: "mu", prefix: 230 },
    { name: "Mayotte", cc: "yt", prefix: 262 },
    { name: "Mexico", cc: "mx", prefix: 52 },
    { name: "Moldova", cc: "md", prefix: 373 },
    { name: "Monaco", cc: "mc", prefix: 377 },
    { name: "Mongolia", cc: "mn", prefix: 976 },
    { name: "Montenegro", cc: "me", prefix: 382 },
    { name: "Montserrat", cc: "ms", prefix: 1664 },
    { name: "Morocco", cc: "ma", prefix: 212 },
    { name: "Mozambique", cc: "mz", prefix: 258 },
    { name: "Namibia", cc: "na", prefix: 264 },
    { name: "Nauru", cc: "nr", prefix: 674 },
    { name: "Nepal", cc: "np", prefix: 977 },
    { name: "Netherlands", cc: "nl", prefix: 31 },
    { name: "Cura\xE7ao", cc: "cw", prefix: 599 },
    { name: "New Caledonia", cc: "nc", prefix: 687 },
    { name: "New Zealand", cc: "nz", prefix: 64 },
    { name: "Nicaragua", cc: "ni", prefix: 505 },
    { name: "Niger", cc: "ne", prefix: 227 },
    { name: "Nigeria", cc: "ng", prefix: 234 },
    { name: "Niue", cc: "nu", prefix: 683 },
    { name: "Norfolk Island", cc: "nf", prefix: 672 },
    { name: "Northern Mariana Islands", cc: "mp", prefix: 1670 },
    { name: "North Korea", cc: "kp", prefix: 850 },
    { name: "Norway", cc: "no", prefix: 47 },
    { name: "Oman", cc: "om", prefix: 968 },
    { name: "Pakistan", cc: "pk", prefix: 92 },
    { name: "Palau", cc: "pw", prefix: 680 },
    { name: "Palestine", cc: "ps", prefix: 970 },
    { name: "Panama", cc: "pa", prefix: 507 },
    { name: "Papua New Guinea", cc: "pg", prefix: 675 },
    { name: "Paraguay", cc: "py", prefix: 595 },
    { name: "Peru", cc: "pe", prefix: 51 },
    { name: "Philippines", cc: "ph", prefix: 63 },
    { name: "Pitcairn Islands", cc: "pn", prefix: 870 },
    { name: "Poland", cc: "pl", prefix: 48 },
    { name: "Portugal", cc: "pt", prefix: 351 },
    { name: "Puerto Rico", cc: "pr", prefix: 1787 },
    { name: "Qatar", cc: "qa", prefix: 974 },
    { name: "R\xE9union", cc: "re", prefix: 262 },
    { name: "Romania", cc: "ro", prefix: 40 },
    { name: "Russia", cc: "ru", prefix: 7 },
    { name: "Rwanda", cc: "rw", prefix: 250 },
    { name: "Saint Helena", cc: "sh", prefix: 290 },
    { name: "Saint Kitts and Nevis", cc: "kn", prefix: 1869 },
    { name: "Saint Lucia", cc: "lc", prefix: 1758 },
    { name: "Saint Martin", cc: "mf", prefix: 1599 },
    { name: "Saint Pierre and Miquelon", cc: "pm", prefix: 508 },
    { name: "Saint Vincent and the Grenadines", cc: "vc", prefix: 1784 },
    { name: "Samoa", cc: "ws", prefix: 685 },
    { name: "San Marino", cc: "sm", prefix: 378 },
    { name: "S\xE3o Tom\xE9 and Pr\xEDncipe", cc: "st", prefix: 239 },
    { name: "Saudi Arabia", cc: "sa", prefix: 966 },
    { name: "Senegal", cc: "sn", prefix: 221 },
    { name: "Serbia", cc: "rs", prefix: 381 },
    { name: "Seychelles", cc: "sc", prefix: 248 },
    { name: "Falkland Islands", cc: "fk", prefix: 500 },
    { name: "Sierra Leone", cc: "sl", prefix: 232 },
    { name: "Singapore", cc: "sg", prefix: 65 },
    { name: "Slovakia", cc: "sk", prefix: 421 },
    { name: "Slovenia", cc: "si", prefix: 386 },
    { name: "Solomon Islands", cc: "sb", prefix: 677 },
    { name: "Somalia", cc: "so", prefix: 252 },
    { name: "South Africa", cc: "za", prefix: 27 },
    { name: "South Korea", cc: "kr", prefix: 82 },
    { name: "South Sudan", cc: "ss", prefix: 211 },
    { name: "Spain", cc: "es", prefix: 34 },
    { name: "Sri Lanka", cc: "lk", prefix: 94 },
    { name: "Sudan", cc: "sd", prefix: 249 },
    { name: "Suriname", cc: "sr", prefix: 597 },
    { name: "Swaziland", cc: "sz", prefix: 268 },
    { name: "Sweden", cc: "se", prefix: 46 },
    { name: "Switzerland", cc: "ch", prefix: 41 },
    { name: "Syria", cc: "sy", prefix: 963 },
    { name: "Taiwan", cc: "tw", prefix: 886 },
    { name: "Tajikistan", cc: "tj", prefix: 992 },
    { name: "Tanzania", cc: "tz", prefix: 255 },
    { name: "Thailand", cc: "th", prefix: 66 },
    { name: "Togo", cc: "tg", prefix: 228 },
    { name: "Tokelau", cc: "tk", prefix: 690 },
    { name: "Tonga", cc: "to", prefix: 676 },
    { name: "Trinidad and Tobago", cc: "tt", prefix: 1868 },
    { name: "Tunisia", cc: "tn", prefix: 216 },
    { name: "Turkey", cc: "tr", prefix: 90 },
    { name: "Turkmenistan", cc: "tm", prefix: 993 },
    { name: "Turks and Caicos Islands", cc: "tc", prefix: 1649 },
    { name: "Tuvalu", cc: "tv", prefix: 688 },
    { name: "Uganda", cc: "ug", prefix: 256 },
    { name: "United Kingdom", cc: "gb", prefix: 44 },
    { name: "Ukraine", cc: "ua", prefix: 380 },
    { name: "United Arab Emirates", cc: "ae", prefix: 971 },
    { name: "Uruguay", cc: "uy", prefix: 598 },
    { name: "United States", cc: "us", prefix: 1 },
    { name: "Uzbekistan", cc: "uz", prefix: 998 },
    { name: "Vanuatu", cc: "vu", prefix: 678 },
    { name: "Venezuela", cc: "ve", prefix: 58 },
    { name: "Vietnam", cc: "vn", prefix: 84 },
    { name: "Virgin Islands", cc: "vi", prefix: 1340 },
    { name: "Wallis and Futuna", cc: "wf", prefix: 681 },
    { name: "Yemen", cc: "ye", prefix: 967 },
    { name: "Zambia", cc: "zm", prefix: 260 },
    { name: "Zimbabwe", cc: "zw", prefix: 263 }
];

module.exports = { categories: categories, countries: countries }